require 'rubygems'
require File.dirname(__FILE__) + '/test_config'
require_relative 'test_config'

require 'httparty'
require 'uri'
require 'net/imap'
require 'net/http'
require 'net/https'
require 'active_support/all'